# This is a basic workflow to help you get started with Actions
# Source: https://github.com/athul/athul
# Source: https://github.com/athul/waka-readme
# Source: https://github.com/anmol098/anmol098/blob/master/.github/workflows/update-stats.yml

# This is a basic workflow to help you get started with Actions

name: Waka Readme

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_EDITORS: True
          SHOW_PROJECTS: True
          SHOW_DAYS_OF_WEEK: True
